### ISSUE TITLE
Forgot to put nova-apex-chart in dist?

### ISSUE THREAD

**Issue by FrodeMMeling** [dcasia/nova-apex-chart#1]
Hello
Have you forgot to put nova-apex-chart.js in dist folder?

I had to cd into your plugin and run npm install && npm run dev to get it to load.

**Comment by milewski** [comment]
@MaxResolution can you fix this?

**Comment by max-yilang** [comment]
fixed https://github.com/dcasia/nova-apex-chart/commit/9a3d47ae3656445523d81dbddade1da90d46fc22
